### ISSUE TITLE
Text flickering on shipped web app

### ISSUE THREAD

**Issue by codingiswhyicry** [SahilDShaw/flutter-gradient-animation-text#1]
Hi, thank you so much for building this. I implemented it within a package used within a couple of different apps and websites.

On debug mode, there's no issues with the gradient. However, on deploy to production / release mode, the gradient text keeps on bugging out and often flickers around. Please let me know if this can be recreated / fixed, or if there is no additional support associated with this package. 

I'm using Safari and the html build renderer and am not seeing error messages within the developer console in browser, nor while running on localhost. 

You can find the example websites here: 
- https://withaetheria.org
- https://withverena.org

My code: 

```
class HeadingOneText extends StatelessWidget {
  final String data;
  final decorationPriority textColor;

  const HeadingOneText({
    required this.data,
    required this.textColor,
  });

  @override
  Widget build(BuildContext context) {
    return GradientAnimationText(
      text: Text(data,
          style: heading1().copyWith(
              color: coloration.decorationColor(decorationVariant: textColor)),
          semanticsLabel: data),
      colors: [
        coloration.contrastColor().withOpacity(0.9),
        coloration.contrastColor().withOpacity(0.8),
        coloration.contrastColor().withOpacity(0.7),
        coloration.contrastColor().withOpacity(0.4),
        coloration.contrastColor().withOpacity(0.7),
        coloration.contrastColor().withOpacity(0.9),
        //coloration.contrastColor().withOpacity(0.3),
      ],
      duration: const Duration(seconds: 6),
    );
  }
}
```

**Comment by SahilDShaw** [comment]
Please don't pass any text color to the Text() widget. Like this:
```
GradientAnimationText(
      text: Text(
        data,
        semanticsLabel: data,
      ),
      colors: [
        coloration.contrastColor().withOpacity(0.9),
        coloration.contrastColor().withOpacity(0.8),
        coloration.contrastColor().withOpacity(0.7),
        coloration.contrastColor().withOpacity(0.4),
        coloration.contrastColor().withOpacity(0.7),
        coloration.contrastColor().withOpacity(0.9),
        //coloration.contrastColor().withOpacity(0.3),
      ],
      duration: const Duration(seconds: 6),
    );
```
However, the GradientAnimationText widget automatically eliminates any color passed to it via the Text widget and replaces it with 'Colors.white', there might be an issue if you pass a color using 'style' parameter.
If the problem persists, then kindly send the class definitions for 'decorationPriority' and 'coloration' with screen recording of the issue here for more clarity.
Let me know if you make any progress.
Thank You

**Comment by SahilDShaw** [comment]
Since there has been no update on the issue for over a month, I'm closing this issue.
